services:
  nexus-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - nexus-db
    environment:
      - POSTGRES_DB=nexus
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./uploads:/app/uploads

  nexus-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - nexus-app

  nexus-db:
    # Using the PostgreSQL image from Amazon ECR Public Gallery
    image: public.ecr.aws/docker/library/postgres:15
    environment:
      - POSTGRES_DB=nexus
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - nexus-db-data:/var/lib/postgresql/data

volumes:
  nexus-db-data:
