services:
  nexus-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - nexus-db
    environment:
      - POSTGRES_DB=nexus
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./uploads:/app/uploads
  nexus-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=nexus
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - nexus-db-data:/var/lib/postgresql/data

volumes:
  nexus-db-data:
