server:
  servlet:
    context-path: /nexus/api

spring:
  application:
    name: nexus
  datasource:
    url: jdbc:postgresql://nexus-db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

file:
  upload-dir: ./uploads

app:
  jwt:
    # IMPORTANT: This is a sample key. Generate a new secure random key for your production environment.
    # You can use an online generator or a command like: openssl rand -base64 32
    secret: bXlzdXBlcnNlY3JldGtleW15c3VwZXJzZWNyZXRrZXlteXN1cGVyc2VjcmV0a2V5MTIz
    expiration-ms: 86400000 # 24 hours
